# Generated by Django 2.0.6 on 2019-03-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('image_URL', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
